#!/bin/bash

LANG="C"

RANDOM_GEN_USERNAME_LENGTH=${RANDOM_GEN_USERNAME_LENGTH:=32}
RANDOM_GEN_PASSWORD_LENGTH=${RANDOM_GEN_PASSWORD_LENGTH:=511}

RANDOM_GEN_USERNAME=""
RANDOM_GEN_PASSWORD=""

CHARACTER_DIGEST="1538607249"
CHARACTER_DOWNCASE="uwnmertyqiojklzxcpasdfghvb"
CHARACTER_OTHER="E\`R!@T)X#I\$S%DF^&H:JK-Z;YC_=+}B.N\"M{~]/Q(W[O|P>A,GV<L'U"


function random_gen_characters()
{
    RANDOM_CHAR_TMP="${1:-${CHARACTER_DIGEST}${CHARACTER_DOWNCASE}}"

    local RANDOM_COUNTER=${2:-1024}
    local RANDOM_CHAR_TMP_GEN=""
    local RANDOM_CHAR_TMP_LEN=${#RANDOM_CHAR_TMP}

    for (( n = 0; n < $RANDOM_COUNTER; n++ ))
    do
        local I=$RANDOM

        if [ "${I}" -eq "$(( (${I}/2) * 2 ))" ]
        then
            for (( i = 1; i < $RANDOM_CHAR_TMP_LEN; i++ ))
            do
                RANDOM_CHAR_TMP="${RANDOM_CHAR_TMP:0:$RANDOM_CHAR_TMP_LEN-i-1}${RANDOM_CHAR_TMP: -i:i+1}${RANDOM_CHAR_TMP:$RANDOM_CHAR_TMP_LEN-i-1:1}"
            done
        fi

        for (( i = 0; i < $RANDOM_CHAR_TMP_LEN; i++ ))
        do
            RANDOM_CHAR_TMP_GEN="${RANDOM_CHAR_TMP:$(($RANDOM % ${#RANDOM_CHAR_TMP})):1}${RANDOM_CHAR_TMP_GEN}"
            RANDOM_CHAR_TMP="${RANDOM_CHAR_TMP//${RANDOM_CHAR_TMP_GEN:0:1}}"
        done

        RANDOM_CHAR_TMP="$RANDOM_CHAR_TMP_GEN"
        RANDOM_CHAR_TMP_GEN=""
    done
}

function random_gen_username()
{
    random_gen_characters

    USERNAME_CHARACTERS="$RANDOM_CHAR_TMP"
    USERNAME_CHARACTERS_SIZE=${#USERNAME_CHARACTERS}

    # Definition of first random letter
    RANDOM_GEN_USERNAME="${CHARACTER_DOWNCASE:$(($RANDOM % ${#CHARACTER_DOWNCASE})):1}"
    RANDOM_GEN_USERNAME="${RANDOM_GEN_USERNAME}${USERNAME_CHARACTERS//${RANDOM_GEN_USERNAME:0:1}}"

    for (( u = 0; u < $(( ${RANDOM_GEN_USERNAME_LENGTH}/${USERNAME_CHARACTERS_SIZE} )); u++ ))
    do
        random_gen_characters

        USERNAME_CHARACTERS="$RANDOM_CHAR_TMP"
        RANDOM_GEN_USERNAME="${RANDOM_GEN_USERNAME}${USERNAME_CHARACTERS}"
    done

    echo "${RANDOM_GEN_USERNAME:0:${RANDOM_GEN_USERNAME_LENGTH}}"
}

function random_gen_password()
{
    PASSWORD_CHARACTERS="${CHARACTER_DIGEST}${CHARACTER_DOWNCASE}${CHARACTER_OTHER}"
    PASSWORD_CHARACTERS_SIZE=${#PASSWORD_CHARACTERS}

    for (( p = 0; p <= $(( ${RANDOM_GEN_PASSWORD_LENGTH}/${PASSWORD_CHARACTERS_SIZE} )); p++ ))
    do
        random_gen_characters "$PASSWORD_CHARACTERS" 4096

        RANDOM_GEN_PASSWORD="${RANDOM_GEN_PASSWORD}${RANDOM_CHAR_TMP}"
    done

    echo "${RANDOM_GEN_PASSWORD:0:${RANDOM_GEN_PASSWORD_LENGTH}}"
}


random_gen_username
random_gen_password
